#![allow(dead_code)]
use crate::internal::*;
use crate::prelude::*;

/// The current age of the Milky Way.
pub const OUR_GALAXYS_AGE: f32 = 13.61;
/// The current age of the universe.
pub const OUR_GALAXYS_NAME: &str = "Milky Way";
/// The current age of the universe.
pub const OUR_GALAXYS_CATEGORY: GalaxyCategory = GalaxyCategory::Spiral(16203, 160);
/// The current age of the universe.
pub const OUR_GALAXYS_SUB_CATEGORY: GalaxySubCategory = GalaxySubCategory::BarredSpiral;
/// The current age of the universe.
pub const NO_SPECIAL_TRAIT: GalaxySpecialTrait = GalaxySpecialTrait::NoPeculiarity;
/// TODO List of all galaxies in our local group
pub const LOCAL_GROUP_GALAXIES: [GalaxyWithoutTraits; 38] = [
    GalaxyWithoutTraits {
        index: 0,
        name: OUR_GALAXYS_NAME,
        age: OUR_GALAXYS_AGE,
        is_dominant: false,
        is_major: true,
        category: OUR_GALAXYS_CATEGORY,
        sub_category: OUR_GALAXYS_SUB_CATEGORY,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 1,
        name: "Andromeda",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Spiral(23280, 230),
        sub_category: OUR_GALAXYS_SUB_CATEGORY,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 2,
        name: "Triangulum",
        age: -1.0,
        is_dominant: false,
        is_major: false,
        category: GalaxyCategory::Spiral(9370, 94),
        sub_category: GalaxySubCategory::FlatSpiral,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 3,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 4,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 5,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 6,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 7,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 8,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 9,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 10,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 11,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 12,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 13,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 14,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 15,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 16,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 17,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 18,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 19,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 20,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 21,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 22,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 23,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 24,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 25,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 26,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 27,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 28,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 29,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 30,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 31,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 32,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 33,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 34,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 35,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 36,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
    GalaxyWithoutTraits {
        index: 37,
        name: "TODO",
        age: -1.0,
        is_dominant: false,
        is_major: true,
        category: GalaxyCategory::Irregular(10, 10, 10),
        sub_category: GalaxySubCategory::DwarfAmorphous,
        first_trait: NO_SPECIAL_TRAIT,
        second_trait: NO_SPECIAL_TRAIT,
        third_trait: NO_SPECIAL_TRAIT,
    },
];

/// Data used to calculate a universe's age.
#[derive(Clone, PartialEq, PartialOrd, Debug, Default, Serialize, Deserialize)]
pub struct GalaxyWithoutTraits<'a> {
    /// The numeric identifier of this galaxy in its neighborhood.
    pub index: u16,
    /// The name of this galaxy.
    pub name: &'a str,
    /// The age of this galaxy in billions of years.
    pub age: f32,
    /// Is this galaxy a dominant one in its cluster?
    pub is_dominant: bool,
    /// Is this galaxy a major one in its neighborhood?
    pub is_major: bool,
    /// In what category this galaxy belongs to.
    pub category: GalaxyCategory,
    /// In what sub-category this galaxy belongs to.
    pub sub_category: GalaxySubCategory,
    /// The first peculiarity this galaxy has, if any.
    pub first_trait: GalaxySpecialTrait,
    /// The second peculiarity this galaxy has, if any.
    pub second_trait: GalaxySpecialTrait,
    /// The third peculiarity this galaxy has, if any.
    pub third_trait: GalaxySpecialTrait,
}
/// Pairs traits that are incompatible with one another.
#[derive(
    Clone, Eq, PartialEq, Ord, PartialOrd, Debug, Hash, SmartDefault, Serialize, Deserialize,
)]
pub struct OppositeTraits(pub Vec<GalaxySpecialTrait>, pub Vec<GalaxySpecialTrait>);

/// Generates a list of pairs of incompatible traits.
pub fn get_opposite_traits() -> Vec<OppositeTraits> {
    vec![
        OppositeTraits(
            vec![GalaxySpecialTrait::Younger],
            vec![GalaxySpecialTrait::Older],
        ),
        OppositeTraits(
            vec![GalaxySpecialTrait::Dusty],
            vec![GalaxySpecialTrait::MetalPoor],
        ),
        OppositeTraits(
            vec![GalaxySpecialTrait::GasPoor],
            vec![GalaxySpecialTrait::GasRich],
        ),
        OppositeTraits(
            vec![GalaxySpecialTrait::Compact(0)],
            vec![GalaxySpecialTrait::Expansive(0)],
        ),
        OppositeTraits(
            vec![GalaxySpecialTrait::SubSize(0)],
            vec![GalaxySpecialTrait::SuperSize(0)],
        ),
        OppositeTraits(
            vec![GalaxySpecialTrait::Starburst],
            vec![GalaxySpecialTrait::Dead, GalaxySpecialTrait::Dormant],
        ),
    ]
}
