[package]
name = "planet_generator"
version = "0.0.3-pre-alpha"
edition = "2021"
description = "[WIP] Generates data for galaxies, sectors, solar systems, planets and their inhabitants (Check README for features list)."
license = "MIT"

[dependencies]
seeded_dice_roller = "0.1.3"
log = "0.4.17"
simple_logger = "4.0.0"
serde = { version = "1.0.147", features = ["derive", "rc"] }
smart-default = "0.6.0"
