name: "Cargo Update"
on:
  schedule:
    - cron: "0 0 * * 1" # Runs every Monday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow
env:
  CARGO_TERM_COLOR: always
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Generate date for branch
        id: date
        run: echo "DATE=$(date +%Y%m%d)" >> $GITHUB_ENV

      - name: Ensure EOL in Cargo.toml
        run: |
            echo "# Test" >> Cargo.toml

      - name: Update Cargo dependencies
        run: cargo update

      - name: Check if there are changes
        run: |
          git config --global user.name "dependabot[bot]"
          git config --global user.email "dependabot@github.com"
          git diff
          if [ "$(git status --porcelain)" != "" ]; then
            git checkout -b cargo-update-${{ env.DATE }}
            git add .
            git commit -m "Full cargo update"
            git push origin cargo-update-${{ env.DATE }}
          else
            echo "No changes detected"
          fi

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.5
        with:
          branch: cargo-update-${{ env.DATE }}
          title: "Full cargo update"
          body: "This pull request updates all dependencies."
          labels: dependencies
          reviewers: lto
